package scholar

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
)

var slugUnsafe = regexp.MustCompile(`[^a-z0-9._-]+`)
var permalinkField = regexp.MustCompile(`:[a-z_]+`)

func detailSlug(key string) string {
	slug := slugUnsafe.ReplaceAllString(strings.ToLower(key), "-")
	return strings.Trim(slug, "-.")
}

func detailURL(options Options, entry Entry) string {
	if options.DetailsPermalink == "" {
		return "/" + path.Join(strings.Trim(options.DetailsDir, "/"), detailSlug(entry["key"])) + "/"
	}
	return permalinkField.ReplaceAllStringFunc(options.DetailsPermalink, func(field string) string {
		switch field {
		case ":details_dir":
			return strings.Trim(options.DetailsDir, "/")
		case ":extension":
			return "/"
		case ":doi":
			return detailSlug(firstNonempty(entry["doi"], entry["key"]))
		default:
			return detailSlug(entry[strings.TrimPrefix(field, ":")])
		}
	})
}

func repositoryLinks(options Options, key string) (map[string]string, error) {
	delimiter := options.RepositoryDelimiter
	if delimiter == "" {
		delimiter = "."
	}
	if strings.Contains(key, delimiter) {
		return nil, fmt.Errorf("citation key %q contains repository delimiter %q", key, delimiter)
	}
	baseURL := options.RepositoryURL
	if baseURL == "" {
		rel := filepath.ToSlash(filepath.Clean(options.Repository))
		if !strings.HasPrefix(rel, "static/") {
			return nil, fmt.Errorf("--repository-url is required when repository is outside static/")
		}
		baseURL = "/" + strings.TrimPrefix(rel, "static/")
	}
	files, err := os.ReadDir(options.Repository)
	if err != nil {
		return nil, err
	}
	links := make(map[string]string)
	prefix := key + delimiter
	for _, file := range files {
		if file.IsDir() || !strings.HasPrefix(file.Name(), prefix) {
			continue
		}
		extension := strings.TrimPrefix(file.Name(), prefix)
		if extension == "" {
			continue
		}
		links[extension] = strings.TrimRight(baseURL, "/") + "/" + url.PathEscape(file.Name())
	}
	return links, nil
}

// prepareDetails validates and stages pages for the default bibliography.
// Only files marked as generated by this tool are removed on a later run.
func prepareDetails(root, directory string, entries []Record, files map[string][]byte) error {
	if directory == "" {
		return nil
	}
	clean := filepath.Clean(filepath.FromSlash(directory))
	if filepath.IsAbs(clean) || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
		return fmt.Errorf("details directory %q must stay within content", directory)
	}
	target := filepath.Join(root, filepath.FromSlash(strings.Trim(directory, "/")))
	const marker = "<!-- Generated by Hugo Scholar. Do not edit. -->"
	current := make(map[string]bool, len(entries))
	urls := make(map[string]string, len(entries))
	for _, record := range entries {
		key := record.Entry["key"]
		if previous, exists := urls[record.DetailURL]; exists {
			return fmt.Errorf("detail page URL %q is shared by %q and %q", record.DetailURL, previous, key)
		}
		urls[record.DetailURL] = key
		slug := detailSlug(key)
		if slug == "" {
			return fmt.Errorf("citation key %q cannot form a detail page path", key)
		}
		name := slug + ".md"
		if current[name] {
			return fmt.Errorf("detail page path collision for citation key %q", key)
		}
		current[name] = true
		file := filepath.Join(target, name)
		if content, err := os.ReadFile(file); err == nil && !strings.Contains(string(content), marker) {
			return fmt.Errorf("refusing to overwrite non-generated detail page %s", file)
		} else if err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	for _, record := range entries {
		key := record.Entry["key"]
		file := filepath.Join(target, detailSlug(key)+".md")
		title, _ := json.Marshal(Clean(record.Entry["title"]))
		quotedKey, _ := json.Marshal(key)
		quotedURL, _ := json.Marshal(record.DetailURL)
		content := fmt.Sprintf("---\ntitle: %s\ntype: scholar\nscholar_key: %s\nurl: %s\n---\n%s\n", title, quotedKey, quotedURL, marker)
		if _, exists := files[file]; exists {
			return fmt.Errorf("multiple generated pages target %s", file)
		}
		files[file] = []byte(content)
	}
	oldFiles, err := filepath.Glob(filepath.Join(target, "*.md"))
	if err != nil {
		return err
	}
	for _, file := range oldFiles {
		if current[filepath.Base(file)] {
			continue
		}
		content, err := os.ReadFile(file)
		if err != nil {
			return err
		}
		if strings.Contains(string(content), marker) {
			files[file] = nil
		}
	}
	return nil
}
